### ISSUE TITLE
Deceptive site ahead

### ISSUE THREAD

**Issue by Catalinu23** [ciprisamoila/Epsilon#1]
After I mine 10 epsilon, there is an error saying "Deceptive site ahead".

**Comment by ciprisamoila** [comment]
You should click "Ignore the risk", and everything will work just fine. Then you will be redirected to a very trusted Spanish bank, where we invite you to write down all your personal information. In a few days you will receive the promised money, unless we will run away and leave your bank account empty. Just joking :grin: . As a very honest Romanian company would say, "You can sleep peacefully, because we are taking care of your money".
